spring:
  application:
    name: acopios
  jooq.sql-dialect: Postgres
  datasource:
    url: jdbc:postgresql://localhost:5433/localenv
    username: localenv
    password: localenv
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  graphql:
    graphiql:
      enabled: true

spring.jpa.properties.hibernate.format_sql: true
springdoc.swagger-ui.path: /swagger-ui.html
springdoc.show-actuator: true
