package gymtrack;

public enum ErrorCodes {
	NOT_FOUND, UNAUTHENTICATED, UNAUTHOTIZED, VALIDATION_ERROR, ALREADY_FOUND, REQUEST_ERROR, UNSUPPORTED_MEDIA_TYPE, INTERNAL_ERROR, METHOD_NOT_ALLOWED, ENDPOINT_NOT_FOUND, NOT_ACCEPTABLE,
}
